name: Magisk Build

on:
  workflow_dispatch:
    inputs:
      MAGISK_REPO:
        description: 'Magisk Repository'
        required: true
        default: 'https://github.com/topjohnwu/Magisk'
      MAGISK_BRANCH:
        description: 'Magisk Repository Branch'
        required: true
        default: 'v28.1'

jobs:
  build:
    name: Build Magisk
    runs-on: ubuntu-latest
    env:
      SCCACHE_DIRECT: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Clone Magisk
        run: |
          git clone --recurse-submodules ${{ inputs.MAGISK_REPO }} -b ${{ inputs.MAGISK_BRANCH }} ./Magisk
          echo "MAGISK_VERS=$(awk -F'=' '/magisk.versionCode/ {print $2}' Magisk/gradle.properties)" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Set up sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}
          max-size: 10000M

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Set up NDK
        run: cd Magisk && python build.py -v ndk
        shell: bash

      - name: Setup environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install --only-upgrade libstdc++6 -y

      - name: Apply Patch
        run: |
          cd Magisk
          curl -o native/src/core/scripting.cpp https://vip.123pan.cn/1814215835/21694316

      - name: Build release
        continue-on-error: true
        run: cd Magisk && ./build.py -vr all && mv out/app-release.apk out/napp-release.apk

      - name: Build debug
        continue-on-error: true
        run: cd Magisk && ./build.py -v all && mv out/app-debug.apk out/napp-debug.apk

      - name: Patch2
        continue-on-error: true
        run: cd Magisk && curl -o native/src/core/su/su_daemon.cpp https://vip.123pan.cn/1814215835/21694324

      - name: Build release
        continue-on-error: true
        run: cd Magisk && ./build.py -vr all

      - name: Build debug
        continue-on-error: true
        run: cd Magisk && ./build.py -v all

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Magisk/out/napp-release.apk
            Magisk/out/napp-debug.apk
            Magisk/out/app-release.apk
            Magisk/out/app-debug.apk
          name: Unofficial Magisk Build Release v${{ env.MAGISK_VERS }}
          tag_name: ${{ github.run_id }}
          body: |
            ## Resources
            - [Magisk Repository](${{ inputs.MAGISK_REPO }}/tree/${{ inputs.MAGISK_BRANCH }})
            ## Available Downloads
            - Release, for normal usage.
            - Debug, solely for debugging purposes.
            ## Notes
            - I, carlodandan, won't entertain any flashing/app/patching issue. Contact whoever the maintainer of the Magisk repository you used for building. Again, the builder you used is for personal use only. I am not responsible with any of the error upon flashing or patching.

      - name: Stop gradle daemon
        continue-on-error: true
        run: cd Magisk && ./gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: Magisk/out
          compression-level: 9

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-symbols
          path: Magisk/app/build/outputs
          compression-level: 9