name: Magisk Build (Very Legacy)

on:
  workflow_dispatch:
    inputs:
      MAGISK_REPO:
        description: 'Magisk Repository'
        required: true
        default: 'https://github.com/zcg9783/Magisk'
      MAGISK_BRANCH:
        description: 'Magisk Repository Branch'
        required: true
        default: 'v22.1'

jobs:
  build:
    name: Build Magisk
    runs-on: ubuntu-22.04
    env:
      SCCACHE_DIRECT: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Clone Magisk
        run: |
          git clone --depth=1 --recurse-submodules ${{ inputs.MAGISK_REPO }} -b ${{ inputs.MAGISK_BRANCH }} Magisk
          echo "MAGISK_VERS=$(awk -F'=' '/magisk.versionCode/ {print $2}' Magisk/gradle.properties)" >> $GITHUB_ENV
          ls -la Magisk/app/build.gradle
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Configure Repositories
        run: |
          sed -i "/allprojects {/a\    repositories {\n        google()\n        mavenCentral()\n        maven { url 'https://jitpack.io' }\n    }" Magisk/build.gradle
          sed -i "/dependencies {/a\    implementation 'org.koin:koin-core:2.1.6'\n    implementation 'org.koin:koin-android:2.1.6'\n    implementation 'org.koin:koin-androidx-viewmodel:2.1.6'" Magisk/app/build.gradle

      - name: Set up NDK
        run: |
          cd Magisk
          python build.py -v ndk

      - name: Build artifacts
        run: |
          cd Magisk
          ./gradlew clean
          ./gradlew assemble --refresh-dependencies --stacktrace
          ./build.py -vr all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: magisk-build-${{ github.run_id }}
          path: |
            Magisk/out/*.apk
            Magisk/native/out/**/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          tag_name: magisk-${{ env.MAGISK_VERS }}
          name: "Magisk ${{ env.MAGISK_VERS }} Build"
          body: |
            Unofficial build from ${{ inputs.MAGISK_REPO }}@${{ inputs.MAGISK_BRANCH }}
            Generated at ${{ github.run_id }}
          files: |
            Magisk/out/app-release.apk
            Magisk/out/stub-release.apk
          draft: false
          prerelease: false